alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      # 強制指定一個存在的 receiver
      receiver: 'telegram-notif'
    receivers:
    - name: 'telegram-notif'
      telegram_configs:
      - bot_token: '8220650877:AAGVopbAY2oDpg3x0RZ3EuLRsN4kqsbqbv8'
        chat_id: 7356555732
        send_resolved: true
    # 增加一個空接收器，防止 Operator 報錯找不到 null
    - name: 'null'