apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-web-chart.fullname" . }}
  labels:
    {{- include "my-web-chart.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    # --- 必須新增這一段 ---
    - port: 9113
      targetPort: 9113
      protocol: TCP
      name: http-metrics
    # ----------------------
  selector:
    {{- include "my-web-chart.selectorLabels" . | nindent 4 }}
